name = "midnight-travel-consulting"
compatibility_date = "2026-07-26"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "midnight-travel-consulting"
database_id = "d66ed0d4-08c6-4ee9-8fec-c038ade12b51"
